Code commenting on the Python wrapper
StrijpT-Ellie/contour-wall pull request #16
Opened 2024-05-16 21:50 UTC by Bash-04

Created all code comments in the Python Wrapper + fixed hsv_to_rgb conversion function

2024-05-16 21:52 UTC, Bash-04 commented
@WouterPennings, I found out that the hsv_to_rgb conversion function wasn't given the expected results. So I recreated the code and commented out the old code. If I didn't do it right you can just change it back, if I did do it right then it's fixed now.

2024-05-17 09:47 UTC, WouterPennings requested changes

2024-05-17 09:47 UTC, WouterPennings commented on lib/wrappers/python/contourwall.py
> +        fill_solid is a function that fills the entire ContourWall with one single color.
This one can be yeeted, as it is the same as the one below it.

2024-05-17 09:47 UTC, WouterPennings commented on lib/wrappers/python/contourwall.py
>  def hsv_to_rgb(hue: int, saturation: float, value: float) -> tuple[int, int, int]:
This function shoul be replaced with this. Make sure you improve the naming and such


```python
def hsv_to_rgb(h, s, v):
    h /= 360
    s /= 100
    v /= 100
    
    if s == 0.0: return v, v, v
        
    i = int(h*6.0) # XXX assume int() truncates!
    f = (h*6.0) - i
    i = i%6
    
    p = round((v*(1.0 - s)) * 255)
    q = round((v*(1.0 - s*f)) * 255)
    t = round((v*(1.0 - s*(1.0-f))) * 255)
    v = round(v*255)
    
    if i == 0:
        return v, t, p
    if i == 1:
        return q, v, p
    if i == 2:
        return p, v, t
    if i == 3:
        return p, q, v
    if i == 4:
        return t, p, v
    if i == 5:
        return v, p, q
```

2024-05-17 09:47 UTC, WouterPennings commented on lib/wrappers/python/contourwall.py
> +    #     return int(value * 255), int(p * 255), int(q * 255)
Can be removed

2024-05-17 09:47 UTC, WouterPennings commented on lib/wrappers/python/demo.py
> +
Should also be removed

2024-05-17 09:49 UTC, WouterPennings commented on lib/wrappers/python/contourwall.py
>  def hsv_to_rgb(hue: int, saturation: float, value: float) -> tuple[int, int, int]:
make sure you also mention in a comment that we stole this implementation from Colorsys:

https://github.com/python/cpython/blob/3.12/Lib/colorsys.py

2024-05-21 07:30 UTC, WouterPennings approved these changes
Vere noice @Bash-04

2024-05-21 07:30 UTC, merged